version: "3.8"
services:
  mysql_dev:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql_data:/var/lib/mysql
    networks:
      - dev_network

  phpmyadmin_dev:	
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql_dev
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8081:80"
    depends_on:
      - mysql_dev
    networks:
      - dev_network

  xampp_dev:
    image: tomsik68/xampp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/brechot/einstein/api:/www
    networks:
      - dev_network

  spring_app:
    build:
     context: ./ProjetoEcommerce
     dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_dev:3306/ecommerce_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - mysql_dev
    networks:
      - dev_network
      
  django_app:
    build: ./djangoEcommerce
    ports:
      - "8000:8000"
    volumes:
      - /home/brechot/einstein/api/djangoEcommerce:/app
    environment:
      DJANGO_SETTINGS_MODULE: src.settings
      API_URL: http://spring_app:8080
    depends_on:
      - spring_app
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
